version: '3.8'

networks:
  cah:

services:
  app:
    image: node:18-alpine
    working_dir: /usr/src/app/
    ports:
      - 3000:3000
    volumes:
      - ./src/:/usr/src/app/
    command: npm run start:dev
    networks:
      - cah
  
  ngrok:
    image: ngrok/ngrok:3-alpine
    ports:
      - 4040:4040
    command: http --authtoken ${NGROK_TOKEN} app:3000
    depends_on:
      - app
    networks:
      - cah
  
  npm:
    image: node:18-alpine
    working_dir: /usr/src/app/
    volumes:
      - ./src/:/usr/src/app/
    entrypoint: 'npm'
    networks:
      - cah